name: GF豆腐店  
avata: /images/rgb.jpg
description: "GreenFaith's blog" 

real_name: Yang Cheng
aka: GreenFaith
mail: godyycheng@gmail.com

markdown: redcarpet
highlighter: pygments

# social 
github: http://github.com/GreenFaith
shixiz: http://shixiz.com
douban: http://www.douban.com/people/greenfaith/
weibo: http://weibo.com/4O4notfound
twitter: https://twitter.com/RGBFaith
